# Generated by Django 4.2.7 on 2025-09-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('isp', 'Internet Service Provider'), ('enduser', 'End User')], default='enduser', max_length=20),
        ),
    ]
