# Generated by Django 4.2.7 on 2025-09-01 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('respondent_type', models.CharField(choices=[('ihl', 'Institution of Higher Learning'), ('isp', 'Internet Service Provider')], max_length=10)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('respondent_name', models.CharField(blank=True, max_length=200)),
                ('respondent_role', models.CharField(blank=True, max_length=100)),
                ('dimension', models.CharField(choices=[('technical', 'Technical Readiness'), ('economic', 'Economic Readiness'), ('socio_cultural', 'Socio-Cultural Readiness'), ('environmental', 'Environmental Readiness'), ('policy_regulatory', 'Policy & Regulatory Readiness'), ('general', 'General')], max_length=20)),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('key_insights', models.TextField(blank=True, help_text='Key insights or themes from this response')),
                ('interview_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-interview_date', '-created_at'],
            },
        ),
    ]
