# Generated by Django 4.2.7 on 2025-09-01 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('university', 'University'), ('college', 'College'), ('technical', 'Technical Institute'), ('other', 'Other')], max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dimension', models.CharField(choices=[('technical', 'Technical Readiness'), ('economic', 'Economic Readiness'), ('socio_cultural', 'Socio-Cultural Readiness'), ('environmental', 'Environmental Readiness'), ('policy_regulatory', 'Policy & Regulatory Readiness')], max_length=20)),
                ('role', models.CharField(choices=[('ihl', 'Institution of Higher Learning'), ('isp', 'Internet Service Provider'), ('both', 'Both')], default='both', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['dimension', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('role', models.CharField(choices=[('lecturer', 'Lecturer'), ('it_support', 'IT Support'), ('admin', 'Administrator'), ('principal', 'Principal'), ('student', 'Student'), ('service_provider', 'Service Provider')], max_length=20)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('county', models.CharField(max_length=100)),
                ('consent_given', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('technical_score', models.FloatField(default=0)),
                ('economic_score', models.FloatField(default=0)),
                ('socio_cultural_score', models.FloatField(default=0)),
                ('environmental_score', models.FloatField(default=0)),
                ('policy_regulatory_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('readiness_level', models.CharField(blank=True, choices=[('very_ready', 'Very Ready (80-100)'), ('not_sure', 'Not Sure (60-79)'), ('not_ready', 'Not Ready (<60)')], max_length=15)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.institution')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.project')),
            ],
        ),
        migrations.CreateModel(
            name='DimensionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('technical', 'Technical Readiness'), ('economic', 'Economic Readiness'), ('socio_cultural', 'Socio-Cultural Readiness'), ('environmental', 'Environmental Readiness'), ('policy_regulatory', 'Policy & Regulatory Readiness')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_comments', to='surveys.submission')),
            ],
            options={
                'ordering': ['dimension'],
                'unique_together': {('submission', 'dimension')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.submission')),
            ],
            options={
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
