# Generated by Django 4.2.7 on 2025-09-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['survey_type', 'dimension', 'order']},
        ),
        migrations.AddField(
            model_name='project',
            name='survey_type',
            field=models.CharField(choices=[('rafsia', 'RAFSIA'), ('isp', 'ISP')], default='rafsia', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='survey_type',
            field=models.CharField(choices=[('rafsia', 'RAFSIA'), ('isp', 'ISP')], default='rafsia', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='strategic_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='survey_type',
            field=models.CharField(choices=[('rafsia', 'RAFSIA'), ('isp', 'ISP')], default='rafsia', max_length=20),
        ),
        migrations.AlterField(
            model_name='dimensioncomment',
            name='dimension',
            field=models.CharField(choices=[('technical', 'Technical Readiness'), ('economic', 'Economic Readiness'), ('socio_cultural', 'Socio-Cultural Readiness'), ('environmental', 'Environmental Readiness'), ('policy_regulatory', 'Policy & Regulatory Readiness'), ('strategic', 'Strategic and Future Outlook')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='dimension',
            field=models.CharField(choices=[('technical', 'Technical Readiness'), ('economic', 'Economic Readiness'), ('socio_cultural', 'Socio-Cultural Readiness'), ('environmental', 'Environmental Readiness'), ('policy_regulatory', 'Policy & Regulatory Readiness'), ('strategic', 'Strategic and Future Outlook')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('text', 'survey_type')},
        ),
    ]
