# Generated by Django 4.2.7 on 2025-09-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='role',
        ),
        migrations.AddField(
            model_name='question',
            name='survey_type',
            field=models.CharField(choices=[('ihl', 'Institution of Higher Learning'), ('isp', 'Internet Service Provider')], default='general', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='dimension',
            field=models.CharField(choices=[('technical', 'Technical Readiness'), ('economic', 'Economic Readiness'), ('socio_cultural', 'Socio-Cultural Readiness'), ('environmental', 'Environmental Readiness'), ('policy_regulatory', 'Policy & Regulatory Readiness')], max_length=50),
        ),
    ]
