# Generated by Django 4.2.7 on 2025-09-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_question_options_remove_question_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['dimension', 'order']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey_type',
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='role',
            field=models.CharField(choices=[('ihl', 'Institution of Higher Learning'), ('isp', 'Internet Service Provider'), ('both', 'Both')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='dimension',
            field=models.CharField(choices=[('technical', 'Technical Readiness'), ('economic', 'Economic Readiness'), ('socio_cultural', 'Socio-Cultural Readiness'), ('environmental', 'Environmental Readiness'), ('policy_regulatory', 'Policy & Regulatory Readiness')], max_length=20),
        ),
    ]
