name: Deploy to Server

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest


steps:
  - name: Checkout code
    uses: actions/checkout@v3

  # ✅ Cache pip dependencies
  - name: Cache pip
    uses: actions/cache@v3
    with:
      path: ~/.cache/pip
      key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      restore-keys: |
        ${{ runner.os }}-pip-

  # ✅ Cache npm dependencies
  - name: Cache npm
    uses: actions/cache@v3
    with:
      path: ~/.npm
      key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      restore-keys: |
        ${{ runner.os }}-npm-

  - name: Deploy via SSH
    uses: appleboy/ssh-action@v0.1.10
    with:
      host: ${{ secrets.SERVER_HOST }}
      username: ${{ secrets.SERVER_USER }}
      key: ${{ secrets.SERVER_SSH_KEY }}
      script: |
        set -e

        echo ">>> Pulling latest code"
        cd /root/opt/Research
        git fetch origin main
        git reset --hard origin/main

        echo ">>> Updating backend"
        cd backend
        source venv/bin/activate
        pip install -r requirements.txt
        python manage.py migrate --noinput
        python manage.py collectstatic --noinput
        deactivate
        sudo systemctl restart rafsia-backend

        echo ">>> Updating frontend"
        cd ../frontend
        npm ci --legacy-peer-deps
        npm run build
        sudo systemctl restart rafsia-frontend

        echo ">>> Deployment finished successfully"
