name: Deploy to Server

on:
  push:
    branches:
      - main   # deploy only when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            echo ">>> Pulling latest code"
            cd /root/opt/Research
            git pull origin main

            echo ">>> Updating backend"
            cd backend
            source ../venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            deactivate
            sudo systemctl restart rafsia-backend

            echo ">>> Updating frontend"
            cd ../frontend
            npm install --omit=dev --legacy-peer-deps
            npm run build
            sudo systemctl restart rafsia-frontend

            echo ">>> Deployment finished successfully"
